matrix:
  include:
    - language: go
      go:
        - "1.14"
      os:
        - linux
      go_import_path: github.com/fluid-cloudnative/fluid
      env:
        - TEST_FLAGS='-race -coverprofile=coverage.txt -covermode=atomic'
      sudo: true
      before_script:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin latest
        - arch=$(go env GOARCH)
        - curl -L https://go.kubebuilder.io/dl/2.3.1/linux/${arch} | tar -xz -C /tmp/
        - sudo mv /tmp/kubebuilder_2.3.1_linux_${arch} /usr/local/kubebuilder
        - export PATH=$PATH:/usr/local/kubebuilder/bin
      script:
        - go test ./pkg/utils/dataset_test.go
        - bash <(curl -s https://codecov.io/bash)


    - language: ruby
      rvm:
        - 2.6
      before_script:
        - gem install mdl
      script:
        - mdl . |grep -v 'vendor\|api_doc'
