matrix:
  include:
    - language: go
      go:
        - "1.14"
      os:
        - linux
      go_import_path: github.com/fluid-cloudnative/fluid
      script:
        - go env -w GO111MODULE=on
        - make csi

