version: 2.1
orbs:
  md-sheriff: nubank/md-sheriff@0.0.5
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    environment:
      TEST_FLAGS: '-race -coverprofile=coverage.txt -covermode=atomic'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: run tests
          command: |
            test -z "$(go fmt ./... 2>/dev/null | tee /dev/stderr)" || (echo "please format Go code with 'gofmt'")
            go vet ./...
      - run: docker build . -t fluid:${CIRCLE_BUILD_NUM}
      - run: docker build . -f Dockerfile.csi -t fluid-csi:${CIRCLE_BUILD_NUM}
  markdownlint:
    docker:
      - image: circleci/ruby:latest
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: gem install mdl
      - run:
          name: Check markdownlint
          command: mdl -c .mdlrc . |grep -v 'vendor\|api_doc'



# maybe later we need to upload output to helm repository
workflows:
  build:
    jobs:
      - markdownlint